services:
  config-renderer:
    image: alpine:latest
    container_name: config-renderer
    restart: "no"
    working_dir: /workspace
    command: sh -c "apk add --no-cache gettext bash && for s in scripts/render_*.sh; do echo \"Running $$s\" && bash $$s; done"
    volumes:
      - .:/workspace
    env_file:
      - .env
    user: "${MY_UID}:${MY_GID}"
  # ======================
  # InfluxDB v2
  # ======================
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "${INFLUXDB_PORT}:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb2
      - ./influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}

  # ======================
  # Grafana
  # ======================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      config-renderer:
        condition: service_completed_successfully
      influxdb:
        condition: service_started
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/alerting:/etc/grafana/provisioning/alerting:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SMTP_ENABLED=${GF_SMTP_ENABLED}
      - GF_SMTP_HOST=smtp.web.de:587
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_USER}
      - GF_SMTP_FROM_NAME=Grafana
      - GF_SMTP_SKIP_VERIFY=true
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_LOG_LEVEL=info
      - GF_SECURITY_ALLOW_EMBEDDING=true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"   # max 50 MB per log file
        max-file: "3"     # keep max 3 files
  # Run container as host user to avoid permission issues
    user: "${MY_UID}:${MY_GID}"

  # ======================
  # Telegraf
  # ======================
  telegraf:
    image: telegraf:1.33
    container_name: telegraf
    restart: always
    depends_on:
      config-renderer:
        condition: service_completed_successfully
      influxdb:
        condition: service_started
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - .env
    environment:
      - HOSTNAME=telegraf
      - INFLUX_TOKEN=${INFLUXDB_TOKEN}
      - INFLUX_ORG=${INFLUXDB_ORG}
      - INFLUX_BUCKET=${INFLUXDB_BUCKET}
      - INFLUX_URL=${INFLUXDB_URL}:{INFLUXDB_PORT}